/******************************************************************************/
/*!
\file   engine.cpp
\author Ryan Hanson
\par    email: iovita\@musicboxgames.net
\par    Project: Full Hearts
\date   9/20/2019
\brief
    WaifuEngine "Engine" class. This is what runs literally everything. In the future
    this may be standardized with a way to load in a game_descriptor file generated by
    the IDE.

\copyright    All content (c) 2018 Music Box Games, all rights reserved.
*/
/******************************************************************************/

#include <algorithm>

#include "include/engine.hpp"
#include "include/threadpool.hpp"

namespace WaifuEngine
{
    engine * engine::instance_ = nullptr;
    bool engine::running = true;

    engine::engine()
    {
        systems_.push_back(threads::threadpool::get_instance());
    }

    engine * engine::get_instance()
    {
        if(instance_ == nullptr)
        {
            instance_ = new engine();
        }
        return instance_;
    }

    void engine::shutdown()
    {
        running = false;
    }

    void engine::start()
    {
        // start up systems
    }

    void engine::update(float dt)
    {
        // update systems
        std::for_each(systems_.begin(), systems_.end(), [dt](base_system * s) -> void {
            s->update(dt);
        });
    }    

    void engine::stop()
    {
        // shutdown all systems
    }

    int engine::exec()
    {
        while(running)
        {
            update(0.0167f);
        }

        std::for_each(systems_.begin(), systems_.end(), [](base_system * s) -> void {
            delete s;
        });
        systems_.clear();        

        return 0;
    }
}
