function(PBCOPY COMPILETARGET COPYTARGET COPYDESTINATION)
add_custom_command(TARGET ${COMPILETARGET} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_directory ${COPYTARGET} ${COPYDESTINATION} DEPENDS ${COMPILETARGET})
endfunction()