/******************************************************************************/
/*!
\file   engine.cpp
\author Ryan Hanson
\par    email: iovita\@musicboxgames.net
\par    Project: Full Hearts
\date   9/20/2019
\brief
    WaifuEngine "Engine" class. This is what runs literally everything. In the future
    this may be standardized with a way to load in a game_descriptor file generated by
    the IDE.

\copyright    All content (c) 2018 Music Box Games, all rights reserved.
*/
/******************************************************************************/

#include "include/engine.hpp"

namespace WaifuEngine
{
    engine * engine::instance_ = nullptr;

    engine::engine() {};

    engine * engine::get_instance()
    {
        if(instance_ == nullptr)
        {
            instance_ = new engine();
        }
        return instance_;
    }

    void engine::start()
    {
        // start up systems
    }

    void engine::update(float dt)
    {
        // update systems
    }    

    void engine::stop()
    {
        // shutdown all systems
    }
}