/******************************************************************************/
/*!
\file   engine.hpp
\author Ryan Hanson
\par    email: iovita\@musicboxgames.net
\par    Project: Full Hearts
\date   9/20/2019
\brief
    WaifuEngine "Engine" class. This is what runs literally everything. In the future
    this may be standardized with a way to load in a game_descriptor file generated by
    the IDE.

\copyright    All content (c) 2018 Music Box Games, all rights reserved.
*/
/******************************************************************************/

#ifndef _WAIFU_ENGINE_H_
#define _WAIFU_ENGINE_H_

namespace WaifuEngine
{
    class engine
    {
    private:
        static engine * instance_;

        engine();
        void update(float dt);
        void start();
        void stop();

    public:
        static engine * get_instance();

        int exec();

    };
}

#endif // _WAIFU_ENGINE_H_